import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { withApiKeyCheck } from '../auth.js';
import { generateQrCode } from '../lib/qr-tool.js';

export function registerQrTools(server: McpServer): void {
  server.registerTool(
    'generate_qr_code',
    {
      title: 'Generate a QR Code',
      description:
        'Generate a QR code PNG image encoding the given text/URL. Use this instead of trying to describe ' +
        'a QR code — it must be a real scannable pixel pattern generated by a QR encoder. Returns the PNG as base64.',
      inputSchema: {
        text: z.string().min(1).describe('The text or URL to encode.'),
        size: z.number().int().min(64).max(1024).optional().describe('Output image size in pixels. Defaults to 256.'),
        errorCorrectionLevel: z.enum(['L', 'M', 'Q', 'H']).optional().describe('Error correction level (higher = more recoverable if damaged, but denser). Defaults to "M".'),
        darkColor: z.string().optional().describe('Hex color for the dark modules. Defaults to "#000000".'),
        lightColor: z.string().optional().describe('Hex color for the light background. Defaults to "#FFFFFF".'),
      },
    },
    withApiKeyCheck(async (opts) => ({ content: [{ type: 'text', text: await generateQrCode(opts) }] })),
  );
}
