import {
  Clock,
  Braces,
  Shield,
  Layers,
  ShieldCheck,
  RefreshCw,
  Fingerprint,
  CalendarRange,
  Calculator,
  Coins,
  Ruler,
  Palette,
  Sparkles,
  Globe,
  Gamepad2,
  ArrowRightLeft,
  Zap,
  Code2,
  FileCode,
  QrCode,
  FileText,
  Lock,
  Timer,
  Regex,
  Database,
  Share2,
  Webhook,
} from 'lucide-react';

export const toolCategories = [
  {
    name: 'Formatters & Viewers',
    items: [
      {
        href: '/json',
        label: 'JSON Viewer',
        icon: Braces,
        desc: 'Format and explore JSON text',
        keywords: ['json formatter', 'json beautifier', 'json prettifier', 'json validator', 'format json', 'beautify json', 'minify json', 'parse json', 'json parser', 'json editor', 'json tree view', 'json lint', 'jsonlint'],
      },
      {
        href: '/jwt',
        label: 'JWT Decoder',
        icon: Shield,
        desc: 'Decode & encode tokens',
        keywords: ['jwt decoder', 'jwt encoder', 'json web token', 'decode jwt', 'jwt parser', 'bearer token decoder', 'jwt debugger', 'token decoder', 'jwt payload', 'auth token viewer', 'jwt verify'],
      },
      {
        href: '/diff-checker',
        label: 'Diff Checker',
        icon: ArrowRightLeft,
        desc: 'Compare text and code side-by-side',
        keywords: ['diff checker', 'text diff', 'compare text', 'code diff', 'file diff', 'diff tool', 'text comparison', 'side by side diff', 'unified diff', 'compare code', 'what changed between two files'],
      },
      {
        href: '/html-preview',
        label: 'HTML / CSS / JS Sandbox',
        icon: Code2,
        desc: 'Live preview HTML/CSS/JS playground',
        keywords: ['html preview', 'css preview', 'js playground', 'live html editor', 'code sandbox', 'html css js editor', 'codepen alternative', 'html renderer', 'frontend playground', 'live code preview'],
      },
      {
        href: '/regex-tester',
        label: 'Regex Tester',
        icon: Regex,
        desc: 'Test patterns with live match highlighting',
        keywords: ['regex tester', 'regex builder', 'regular expression tester', 'regex validator', 'regex debugger', 'pattern matcher', 'regex101 alternative', 'test regex', 'regex match highlighter', 'regex replace tool', 'regexp tester', 'regex cheat sheet'],
      },
      {
        href: '/sql-formatter',
        label: 'SQL Formatter',
        icon: Database,
        desc: 'Beautify & minify SQL queries',
        keywords: ['sql formatter', 'sql beautifier', 'sql prettifier', 'format sql', 'beautify sql', 'sql minifier', 'query formatter', 'mysql formatter', 'postgresql formatter', 'sql linter', 'sql pretty print', 'sequel formatter'],
      },
      {
        href: '/graphql-formatter',
        label: 'GraphQL Formatter',
        icon: Share2,
        desc: 'Format & validate GraphQL queries',
        keywords: ['graphql formatter', 'graphql validator', 'graphql beautifier', 'format graphql query', 'graphql linter', 'gql formatter', 'graphql schema validator', 'prettify graphql', 'graphql syntax checker'],
      },
    ],
  },
  {
    name: 'Converters & Parsers',
    items: [
      {
        href: '/epoch',
        label: 'Epoch Converter',
        icon: Clock,
        desc: 'Unix timestamp converter',
        keywords: ['epoch converter', 'unix timestamp converter', 'unix time', 'timestamp to date', 'date to timestamp', 'epoch time', 'unix epoch', 'convert timestamp', 'current unix time', 'epochconverter'],
      },
      {
        href: '/encoder-decoder',
        label: 'Text Encoder / Decoder',
        icon: ShieldCheck,
        desc: 'Base64, URL, Hex, HTML',
        keywords: ['base64 encode', 'base64 decode', 'b64', 'url encode', 'url decode', 'hex encode', 'hex decode', 'html entity encode', 'encode text', 'decode string', 'text encoder', 'text decoder', 'percent encoding', 'rot13'],
      },
      {
        href: '/converters',
        label: 'Data Format Converter',
        icon: RefreshCw,
        desc: 'CSV, XML, YAML, Markdown parser & live markdown editor',
        keywords: ['csv to json', 'json to csv', 'xml to json', 'json to xml', 'yaml to json', 'json to yaml', 'markdown to html', 'markdown editor', 'markdown previewer', 'md to html', 'html to markdown', 'data format converter', 'csv parser', 'xml parser', 'yaml parser', 'live markdown preview'],
      },
      {
        href: '/text-utils',
        label: 'Text & Case Utility',
        icon: FileText,
        desc: 'Case conversion & analytics',
        keywords: ['case converter', 'uppercase lowercase converter', 'camel case', 'snake case', 'kebab case', 'title case', 'text analytics', 'word counter', 'character counter', 'text case converter', 'capitalize text', 'text statistics'],
      },
      {
        href: '/file-converter',
        label: 'Universal File Converter',
        icon: ArrowRightLeft,
        desc: 'Convert files client-side',
        keywords: ['file converter', 'convert files', 'file format converter', 'document converter', 'image to base64', 'file to text converter', 'client-side file conversion', 'batch file convert'],
      },
    ],
  },
  {
    name: 'Generators',
    items: [
      {
        href: '/calendar',
        label: 'Calendar Planner',
        icon: CalendarRange,
        desc: 'Interactive calendar, task scheduler',
        keywords: ['calendar planner', 'task scheduler', 'calendar app', 'event planner', 'monthly calendar', 'interactive calendar', 'plan tasks', 'agenda planner'],
      },
      {
        href: '/cron',
        label: 'Cron Generator',
        icon: CalendarRange,
        desc: 'Visual cron scheduler',
        keywords: ['cron generator', 'cron expression builder', 'crontab generator', 'cron job creator', 'cron syntax helper', 'visual cron builder', 'schedule generator', 'cron parser', 'cron humanizer', 'crontab syntax'],
      },
      {
        href: '/security-tools',
        label: 'Security & Key Suite',
        icon: Lock,
        desc: 'Passwords, Keys, HMAC, BCrypt, UUIDs',
        keywords: ['password generator', 'random password generator', 'secure key generator', 'hmac generator', 'bcrypt hash', 'uuid generator', 'guid generator', 'unique id generator', 'random id', 'uuid v4', 'identifier generator', 'unique identifier', 'token generator', 'secret key generator', 'hash generator'],
      },
      {
        href: '/qr-barcode',
        label: 'QR & Barcode Creator',
        icon: QrCode,
        desc: 'Generate QR codes and barcodes',
        keywords: ['qr code generator', 'barcode generator', 'qr generator', 'create qr code', 'generate barcode', 'qr code maker', 'barcode maker', 'scan code generator'],
      },
      {
        href: '/lorem-ipsum',
        label: 'Lorem Ipsum',
        icon: FileText,
        desc: 'Generate dummy placeholder text',
        keywords: ['lorem ipsum generator', 'placeholder text generator', 'dummy text generator', 'filler text', 'sample text generator', 'lorem ipsum dolor', 'fake paragraph generator'],
      },
      {
        href: '/fake-address',
        label: 'Fake Person & Address',
        icon: Globe,
        desc: 'Mock test profile datasets',
        keywords: ['fake data generator', 'mock data generator', 'fake address generator', 'fake name generator', 'test data generator', 'dummy profile generator', 'random person generator', 'fake identity generator'],
      },
    ],
  },
  {
    name: 'Calculators & Design',
    items: [
      {
        href: '/calculator',
        label: 'Calculators Suite',
        icon: Calculator,
        desc: 'EMI, Salary, GST, SIP, BMI',
        keywords: ['emi calculator', 'loan calculator', 'salary calculator', 'gst calculator', 'sip calculator', 'bmi calculator', 'finance calculator', 'tax calculator', 'interest calculator'],
      },
      {
        href: '/currency',
        label: 'Currency Exchange',
        icon: Coins,
        desc: 'Exchange rates & offline values',
        keywords: ['currency converter', 'exchange rate calculator', 'forex converter', 'money converter', 'currency exchange rates', 'convert currency offline'],
      },
      {
        href: '/unit-converter',
        label: 'Unit Converter',
        icon: Ruler,
        desc: 'Length, weight, area conversions',
        keywords: ['unit converter', 'length converter', 'weight converter', 'area converter', 'metric converter', 'convert units', 'measurement converter', 'imperial to metric'],
      },
      {
        href: '/color-picker',
        label: 'Color Tool Suite',
        icon: Palette,
        desc: 'Picker, contrast, random palettes',
        keywords: ['color picker', 'hex color picker', 'rgb to hex', 'color contrast checker', 'random color generator', 'color palette generator', 'color converter', 'hsl color picker', 'accessibility contrast checker'],
      },
      {
        href: '/image-tool',
        label: 'Image Optimizer',
        icon: Sparkles,
        desc: 'Compress, scale, filter & generate favicons',
        keywords: ['image compressor', 'image optimizer', 'resize image', 'compress image', 'image converter', 'image quality reducer', 'photo compressor', 'exif viewer', 'favicon generator', 'favicon maker', 'ico generator', 'apple touch icon generator', 'generate favicon', 'site icon creator', 'img', 'image enhancer', 'photo enhancer', 'meta', 'metadata', 'metadata viewer', 'image metadata'],
      },
      {
        href: '/countdown',
        label: 'Countdown & Stopwatch',
        icon: Timer,
        desc: 'Visual timer and lap recorder',
        keywords: ['countdown timer', 'stopwatch', 'timer app', 'lap timer', 'event countdown', 'online timer', 'visual countdown'],
      },
    ],
  },
  {
    name: 'System & Network',
    items: [
      {
        href: '/ip-intel',
        label: 'IP & Identity',
        icon: Globe,
        desc: 'Geo-IP & validation + HTTP Ping',
        keywords: ['ip lookup', 'my ip address', 'geo ip lookup', 'ip address finder', 'what is my ip', 'ip validator', 'http ping', 'ping tool'],
      },
      {
        href: '/speed-test',
        label: 'Speed Test',
        icon: Zap,
        desc: 'Ping, jitter, download, upload',
        keywords: ['internet speed test', 'download speed test', 'upload speed test', 'ping test', 'jitter test', 'bandwidth test', 'network speed checker'],
      },
      {
        href: '/pdf-tools',
        label: 'PDF Suite',
        icon: FileCode,
        desc: 'Merge, split, and password protect',
        keywords: ['merge pdf', 'split pdf', 'password protect pdf', 'pdf tools', 'combine pdf', 'pdf merger', 'pdf splitter', 'encrypt pdf', 'compress pdf'],
      },
      {
        href: '/http-toolkit',
        label: 'HTTP Toolkit',
        icon: Webhook,
        desc: 'Status codes, header inspector, webhook tester',
        keywords: ['http status codes', 'status code reference', 'http header inspector', 'webhook tester', 'webhook.site alternative', 'http response viewer', 'header checker', 'webhook testing tool', 'http status lookup', 'api status codes', 'rest api status codes', 'check response headers'],
      },
      {
        href: '/fun-tools',
        label: 'Fun Utilities',
        icon: Gamepad2,
        desc: 'Coin flip, dice roll, name wheel',
        keywords: ['coin flip', 'dice roller', 'random name picker', 'decision maker', 'random wheel', 'spin wheel'],
      },
    ],
  },
];
