import {
  Clock,
  Braces,
  Shield,
  Layers,
  ShieldCheck,
  RefreshCw,
  Fingerprint,
  CalendarRange,
  Calculator,
  Coins,
  Ruler,
  Palette,
  Sparkles,
  Globe,
  Gamepad2,
  ArrowRightLeft,
  Zap,
  Code2,
  FileCode,
  QrCode,
  FileText,
  Lock,
  Timer,
  Regex,
  Database,
  Share2,
  Webhook,
} from 'lucide-react';

export const toolCategories = [
  {
    name: 'Formatters & Viewers',
    items: [
      {
        href: '/json',
        label: 'JSON Viewer',
        icon: Braces,
        desc: 'Format and explore JSON text',
        keywords: ['json formatter', 'json beautifier', 'json prettifier', 'json validator', 'format json', 'beautify json', 'minify json', 'parse json', 'json parser', 'json editor', 'json tree view', 'json lint', 'jsonlint', 'json to typescript', 'generate typescript interface', 'ts interface from json', 'json to csv', 'csv export', 'jsonpath', 'jsonpath tester', 'jsonpath evaluator', 'sort json keys', 'remove null values', 'escape json string', 'unescape json', 'load large json file', 'json search key value', 'json history'],
      },
      {
        href: '/jwt',
        label: 'JWT Decoder',
        icon: Shield,
        desc: 'Decode & encode tokens',
        keywords: ['jwt decoder', 'jwt encoder', 'json web token', 'decode jwt', 'jwt parser', 'bearer token decoder', 'jwt debugger', 'token decoder', 'jwt payload', 'auth token viewer', 'jwt verify', 'jwt generator', 'sign jwt', 'create jwt token', 'verify jwt signature', 'hs256', 'rs256', 'hmac jwt', 'rsa jwt', 'jwt expiration checker', 'jwt claims', 're-sign token', 'jwt builder'],
      },
      {
        href: '/diff-checker',
        label: 'Diff Checker',
        icon: ArrowRightLeft,
        desc: 'Compare text and code side-by-side',
        keywords: ['diff checker', 'text diff', 'compare text', 'code diff', 'file diff', 'diff tool', 'text comparison', 'side by side diff', 'unified diff', 'compare code', 'what changed between two files', 'inline diff', 'ignore whitespace', 'diff history', 'compare json', 'compare yaml', 'compare xml', 'swap diff sides', 'monaco diff editor'],
      },
      {
        href: '/html-preview',
        label: 'HTML / CSS / JS Sandbox',
        icon: Code2,
        desc: 'Live preview HTML/CSS/JS playground',
        keywords: ['html preview', 'css preview', 'js playground', 'live html editor', 'code sandbox', 'html css js editor', 'codepen alternative', 'html renderer', 'frontend playground', 'live code preview', 'jsfiddle alternative', 'css playground', 'browser sandbox', 'console log viewer', 'starter templates'],
      },
      {
        href: '/regex-tester',
        label: 'Regex Tester',
        icon: Regex,
        desc: 'Test patterns with live match highlighting',
        keywords: ['regex tester', 'regex builder', 'regular expression tester', 'regex validator', 'regex debugger', 'pattern matcher', 'regex101 alternative', 'test regex', 'regex match highlighter', 'regex replace tool', 'regexp tester', 'regex cheat sheet', 'regex replace', 'find and replace regex', 'regex flags', 'capture groups', 'named groups', 'email regex', 'url regex', 'ip regex', 'hex color regex', 'phone regex'],
      },
      {
        href: '/sql-formatter',
        label: 'SQL Formatter',
        icon: Database,
        desc: 'Beautify & minify SQL queries',
        keywords: ['sql formatter', 'sql beautifier', 'sql prettifier', 'format sql', 'beautify sql', 'sql minifier', 'query formatter', 'mysql formatter', 'postgresql formatter', 'sql linter', 'sql pretty print', 'sequel formatter', 'mariadb formatter', 't-sql formatter', 'sql server formatter', 'oracle sql formatter', 'plsql formatter', 'bigquery formatter', 'redshift formatter', 'spark sql formatter', 'sqlite formatter', 'sql keyword case'],
      },
      {
        href: '/graphql-formatter',
        label: 'GraphQL Formatter',
        icon: Share2,
        desc: 'Format & validate GraphQL queries',
        keywords: ['graphql formatter', 'graphql validator', 'graphql beautifier', 'format graphql query', 'graphql linter', 'gql formatter', 'graphql schema validator', 'prettify graphql', 'graphql syntax checker', 'graphql minify', 'graphql schema validation', 'validate graphql query', 'graphql sdl', 'graphql mutation formatter'],
      },
    ],
  },
  {
    name: 'Converters & Parsers',
    items: [
      {
        href: '/epoch',
        label: 'Epoch Converter',
        icon: Clock,
        desc: 'Unix timestamp converter',
        keywords: ['epoch converter', 'unix timestamp converter', 'unix time', 'timestamp to date', 'date to timestamp', 'epoch time', 'unix epoch', 'convert timestamp', 'current unix time', 'epochconverter', 'live unix clock', 'negative timestamp', 'before 1970 epoch', 'start of day timestamp', 'end of day timestamp', 'start of month', 'end of month', 'start of year', 'end of year', 'hh mm ss to milliseconds', 'duration calculator', 'add subtract durations', 'timestamp code snippets', 'python timestamp code', 'java timestamp code', 'timezone converter', 'iana timezone list', 'rfc 2822 date', '24 hour format'],
      },
      {
        href: '/encoder-decoder',
        label: 'Text Encoder / Decoder',
        icon: ShieldCheck,
        desc: 'Base64, URL, Hex, HTML',
        keywords: ['base64 encode', 'base64 decode', 'b64', 'url encode', 'url decode', 'hex encode', 'hex decode', 'html entity encode', 'encode text', 'decode string', 'text encoder', 'text decoder', 'percent encoding', 'rot13', 'binary encoder', 'binary to text', 'octal converter', 'caesar cipher', 'morse code translator', 'morse code converter', 'cipher tool', 'ascii to binary', 'hex to text', 'html entities decoder'],
      },
      {
        href: '/converters',
        label: 'Data Format Converter',
        icon: RefreshCw,
        desc: 'CSV, XML, YAML, Markdown parser & live markdown editor',
        keywords: ['csv to json', 'json to csv', 'xml to json', 'json to xml', 'yaml to json', 'json to yaml', 'markdown to html', 'markdown editor', 'markdown previewer', 'md to html', 'html to markdown', 'data format converter', 'csv parser', 'xml parser', 'yaml parser', 'live markdown preview', 'xml formatter', 'yaml formatter', 'markdown toolbar', 'html sanitizer', 'tsv to json'],
      },
      {
        href: '/text-utils',
        label: 'Text & Case Utility',
        icon: FileText,
        desc: 'Case conversion & analytics',
        keywords: ['case converter', 'uppercase lowercase converter', 'camel case', 'snake case', 'kebab case', 'title case', 'text analytics', 'word counter', 'character counter', 'text case converter', 'capitalize text', 'text statistics', 'pascal case', 'constant case', 'alternating case', 'sentence case converter', 'reading time calculator', 'speaking time calculator', 'word frequency counter', 'character frequency counter', 'paragraph counter', 'sentence counter', 'line counter'],
      },
      {
        href: '/file-converter',
        label: 'Universal File Converter',
        icon: ArrowRightLeft,
        desc: 'Convert files client-side',
        keywords: ['file converter', 'convert files', 'file format converter', 'document converter', 'image to base64', 'file to text converter', 'client-side file conversion', 'batch file convert', 'json to ini', 'ini to json', 'png to webp', 'jpg to png', 'webp to png', 'image format converter', 'svg to png', 'base64 to file', 'drag and drop converter'],
      },
    ],
  },
  {
    name: 'Generators',
    items: [
      {
        href: '/calendar',
        label: 'Calendar Planner',
        icon: CalendarRange,
        desc: 'Interactive calendar, task scheduler',
        keywords: ['calendar planner', 'task scheduler', 'calendar app', 'event planner', 'monthly calendar', 'interactive calendar', 'plan tasks', 'agenda planner', 'export to google calendar', 'export to outlook', 'ics file export', 'icalendar generator', 'calendar json backup', 'event categories', 'upcoming events list'],
      },
      {
        href: '/cron',
        label: 'Cron Generator',
        icon: CalendarRange,
        desc: 'Visual cron scheduler',
        keywords: ['cron generator', 'cron expression builder', 'crontab generator', 'cron job creator', 'cron syntax helper', 'visual cron builder', 'schedule generator', 'cron parser', 'cron humanizer', 'crontab syntax', 'cron translator', 'cron to plain english', 'explain cron expression', 'cron next run time', 'cron presets', 'weekday cron', 'crontab explainer'],
      },
      {
        href: '/security-tools',
        label: 'Security & Key Suite',
        icon: Lock,
        desc: 'Passwords, Keys, HMAC, BCrypt, UUIDs',
        keywords: ['password generator', 'random password generator', 'secure key generator', 'hmac generator', 'bcrypt hash', 'uuid generator', 'guid generator', 'unique id generator', 'random id', 'uuid v4', 'identifier generator', 'unique identifier', 'token generator', 'secret key generator', 'hash generator', 'ulid generator', 'nanoid generator', 'uuid v1 generator', 'uuid v5 generator', 'uuid namespace generator', 'sha1 hmac', 'sha256 hmac', 'sha512 hmac', 'bcrypt verifier', 'bcrypt compare', 'password hash checker', 'uuid decoder', 'uuid v1 timestamp decoder', 'bulk uuid generator', 'download uuid list'],
      },
      {
        href: '/qr-barcode',
        label: 'QR & Barcode Creator',
        icon: QrCode,
        desc: 'Generate QR codes and barcodes',
        keywords: ['qr code generator', 'barcode generator', 'qr generator', 'create qr code', 'generate barcode', 'qr code maker', 'barcode maker', 'scan code generator', 'code128 generator', 'code39 generator', 'ean13 generator', 'upc-a generator', 'codabar generator', 'qr error correction', 'product barcode generator', 'isbn barcode'],
      },
      {
        href: '/lorem-ipsum',
        label: 'Lorem Ipsum',
        icon: FileText,
        desc: 'Generate dummy placeholder text',
        keywords: ['lorem ipsum generator', 'placeholder text generator', 'dummy text generator', 'filler text', 'sample text generator', 'lorem ipsum dolor', 'fake paragraph generator', 'lorem ipsum words', 'lorem ipsum sentences', 'lorem ipsum list', 'lorem ipsum html', 'placeholder list generator'],
      },
      {
        href: '/fake-address',
        label: 'Fake Person & Address',
        icon: Globe,
        desc: 'Mock test profile datasets',
        keywords: ['fake data generator', 'mock data generator', 'fake address generator', 'fake name generator', 'test data generator', 'dummy profile generator', 'random person generator', 'fake identity generator', 'fake credit card generator', 'fake ssn generator', 'fake email generator', 'fake phone number generator', 'fake company generator', 'uk address generator', 'india address generator', 'canada address generator', 'bulk fake data json', 'multi country fake data'],
      },
    ],
  },
  {
    name: 'Calculators & Design',
    items: [
      {
        href: '/calculator',
        label: 'Calculators Suite',
        icon: Calculator,
        desc: 'EMI, Salary, GST, SIP, BMI',
        keywords: ['emi calculator', 'loan calculator', 'salary calculator', 'gst calculator', 'sip calculator', 'bmi calculator', 'finance calculator', 'tax calculator', 'interest calculator', 'scientific calculator', 'percentage calculator', 'amortization calculator', 'amortization schedule', 'age calculator', 'date calculator', 'days between dates', 'date difference calculator', 'add days to date', 'salary converter', 'hourly to salary', 'take-home pay calculator', 'cgst sgst calculator', 'mutual fund calculator', 'sip return calculator'],
      },
      {
        href: '/currency',
        label: 'Currency Exchange',
        icon: Coins,
        desc: 'Exchange rates & offline values',
        keywords: ['currency converter', 'exchange rate calculator', 'forex converter', 'money converter', 'currency exchange rates', 'convert currency offline', 'custom exchange rate', 'edit exchange rates', 'offline currency converter', 'exchange rate chart', 'swap currency', 'currency rate matrix', 'live exchange rates'],
      },
      {
        href: '/unit-converter',
        label: 'Unit Converter',
        icon: Ruler,
        desc: 'Length, weight, area conversions',
        keywords: ['unit converter', 'length converter', 'weight converter', 'area converter', 'metric converter', 'convert units', 'measurement converter', 'imperial to metric', 'volume converter', 'temperature converter', 'celsius to fahrenheit', 'speed converter', 'time converter', 'digital storage converter', 'data size converter', 'byte converter', 'energy converter', 'pressure converter', 'psi to bar', 'kg to lbs', 'feet to meters'],
      },
      {
        href: '/color-picker',
        label: 'Color Tool Suite',
        icon: Palette,
        desc: 'Picker, contrast, random palettes',
        keywords: ['color picker', 'hex color picker', 'rgb to hex', 'color contrast checker', 'random color generator', 'color palette generator', 'color converter', 'hsl color picker', 'accessibility contrast checker', 'cmyk color picker', 'color harmony generator', 'complementary color', 'triadic color scheme', 'analogous colors', 'wcag checker', 'lock color palette', 'hsv color', 'color scheme generator'],
      },
      {
        href: '/image-tool',
        label: 'Image Optimizer',
        icon: Sparkles,
        desc: 'Compress, scale, filter & generate favicons',
        keywords: ['image compressor', 'image optimizer', 'resize image', 'compress image', 'image converter', 'image quality reducer', 'photo compressor', 'exif viewer', 'favicon generator', 'favicon maker', 'ico generator', 'apple touch icon generator', 'generate favicon', 'site icon creator', 'img', 'image enhancer', 'photo enhancer', 'meta', 'metadata', 'metadata viewer', 'image metadata', 'image filter', 'brightness contrast saturation', 'grayscale image', 'blur image', 'aspect ratio lock', 'dominant color extractor', 'extract colors from image', 'exif data reader', 'camera exif', 'jpeg to webp', 'site.webmanifest generator'],
      },
      {
        href: '/countdown',
        label: 'Countdown & Stopwatch',
        icon: Timer,
        desc: 'Visual timer and lap recorder',
        keywords: ['countdown timer', 'stopwatch', 'timer app', 'lap timer', 'event countdown', 'online timer', 'visual countdown', 'pomodoro timer', 'alarm sound timer', 'lap times', 'split times', 'timer presets'],
      },
    ],
  },
  {
    name: 'System & Network',
    items: [
      {
        href: '/ip-intel',
        label: 'IP & Identity',
        icon: Globe,
        desc: 'Geo-IP & validation + HTTP Ping',
        keywords: ['ip lookup', 'my ip address', 'geo ip lookup', 'ip address finder', 'what is my ip', 'ip validator', 'http ping', 'ping tool', 'ipv6 lookup', 'asn lookup', 'isp lookup', 'disposable email checker', 'email validator', 'phone number validator', 'url parser', 'query string parser', 'parse url parameters', 'latency test', 'jitter tester', 'geolocation map'],
      },
      {
        href: '/speed-test',
        label: 'Speed Test',
        icon: Zap,
        desc: 'Ping, jitter, download, upload',
        keywords: ['internet speed test', 'download speed test', 'upload speed test', 'ping test', 'jitter test', 'bandwidth test', 'network speed checker', 'speedometer', 'mbps test', 'cloudflare speed test', 'throughput test', 'speed test history'],
      },
      {
        href: '/pdf-tools',
        label: 'PDF Suite',
        icon: FileCode,
        desc: 'Merge, split, and password protect',
        keywords: ['merge pdf', 'split pdf', 'password protect pdf', 'pdf tools', 'combine pdf', 'pdf merger', 'pdf splitter', 'encrypt pdf', 'compress pdf', 'sign pdf', 'pdf signature', 'esign pdf', 'draw signature', 'text to pdf', 'generate pdf from text', 'extract pdf pages', 'unlock pdf', 'decrypt pdf', 'reorder pdf pages'],
      },
      {
        href: '/http-toolkit',
        label: 'HTTP Toolkit',
        icon: Webhook,
        desc: 'Status codes, header inspector, webhook tester',
        keywords: ['http status codes', 'status code reference', 'http header inspector', 'webhook tester', 'webhook.site alternative', 'http response viewer', 'header checker', 'webhook testing tool', 'http status lookup', 'api status codes', 'rest api status codes', 'check response headers', 'security headers checker', 'compare http responses', 'response diff', 'api test client', 'send test request', 'request replay', 'export as curl', 'mock api response', 'webhook capture', 'response time checker'],
      },
      {
        href: '/fun-tools',
        label: 'Fun Utilities',
        icon: Gamepad2,
        desc: 'Coin flip, dice roll, name wheel',
        keywords: ['coin flip', 'dice roller', 'random name picker', 'decision maker', 'random wheel', 'spin wheel', 'team generator', 'random team splitter', 'group generator', 'dice simulator', 'random number picker', 'wheel of names'],
      },
    ],
  },
];
